### ISSUE TITLE
App Not Compatible with Android Studio 3.0+

### ISSUE THREAD

**Issue by samkitpalecha** [contentful/discovery-app-android#10]
Seems like this app needs to be updated to work for the Latest Android Studio. The apt method is deprecated. I tried fixing it using the compile and annotationProcessor methods but I can't get it to work.

**Comment by mariobodemann** [comment]
Hey,

that is true, I will update this as soon as time permits, but sadly my priorities are on a different project right now. 

If you want to change it, you would need to replace `apt` with the new `annotationProcessor` directive and make sure that for `vault` the `core` is also added to the annotation processing step.

Essentially the changes needed should go along the lines of these changes: https://github.com/contentful/blog-app-android/commit/5f6d45ace1b2ebc6ddbd566bdfeab8c1b07a2294. 

And they will be added as soon as my current project ships. Up until then, feel free to see if you can achieve it by your self, and feel free to reach out in the mean time ...

Greetings, Mario

**Comment by samkitpalecha** [comment]
Thanks for the quick reply. I've already done some of it. I'll try and achieve everything else too and report back.
